export type TaskStatus='Not started'|'In progress'|'Waiting'|'Completed'|'Cancelled';
export interface PortalTask{id:string;title:string;description:string;assignee:string;creator:string;company:string;dueDate:string;priority:'Low'|'Normal'|'High'|'Urgent';status:TaskStatus;category:string;comments:string[];createdAt:string;updatedAt:string;completedAt?:string}
export interface PortalRecord{id:string;kind:'event'|'meeting'|'announcement'|'resource'|'staff'|'governance'|'note';title:string;description:string;date?:string;url?:string;category?:string;company?:string;updatedAt:string;data?:Record<string,unknown>}
const DB='ja-staff-portal',VERSION=1;
const open=()=>new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('tasks'))r.result.createObjectStore('tasks',{keyPath:'id'});if(!r.result.objectStoreNames.contains('records'))r.result.createObjectStore('records',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function all<T>(store:string):Promise<T[]>{const d=await open();return new Promise((resolve,reject)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function put<T>(store:string,value:T){const d=await open();return new Promise<void>((resolve,reject)=>{const r=d.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
export const portalStorage={
 listTasks:()=>all<PortalTask>('tasks'),saveTask:async(task:Partial<PortalTask>&Pick<PortalTask,'title'>)=>{const now=new Date().toISOString();const value:PortalTask={id:task.id??crypto.randomUUID(),title:task.title,description:task.description??'',assignee:task.assignee??'Alfie',creator:task.creator??'Local staff user',company:task.company??'JA Group Services Ltd',dueDate:task.dueDate??'',priority:task.priority??'Normal',status:task.status??'Not started',category:task.category??'General',comments:task.comments??[],createdAt:task.createdAt??now,updatedAt:now,completedAt:task.status==='Completed'?now:undefined};await put('tasks',value);return value;},
 listRecords:()=>all<PortalRecord>('records'),saveRecord:async(record:Omit<PortalRecord,'id'|'updatedAt'>&Partial<Pick<PortalRecord,'id'|'updatedAt'>>)=>{const value={...record,id:record.id??crypto.randomUUID(),updatedAt:new Date().toISOString()} as PortalRecord;await put('records',value);return value;}
};
