/**
 * GET /api/signing/requests/:id/certificate
 * Generate and return an HTML audit certificate for a completed signing request.
 */
import type { Request, Response } from 'express';
import { db } from '../../../../../db/client.js';
import { ja_signing_requests, ja_signing_signers, ja_signing_audit, ja_users, ja_site_settings } from '../../../../../db/schema.js';
import { eq, and, asc } from 'drizzle-orm';
import { resolveSession } from '../../../../auth/_session.js';

export default async function handler(req: Request, res: Response) {
  const userId = await resolveSession(req);
  if (!userId) return res.status(401).json({ success: false, error: 'Please sign in to continue.', code: 'NOT_AUTHENTICATED' });

  const { id } = req.params;
  const [request] = await db
    .select()
    .from(ja_signing_requests)
    .where(and(eq(ja_signing_requests.uuid, id), eq(ja_signing_requests.userId, userId as number)))
    .limit(1);

  if (!request) return res.status(404).json({ success: false, error: 'Signing request not found.' });

  const [signers, audit, ownerRows, siteNameRow] = await Promise.all([
    db.select().from(ja_signing_signers).where(eq(ja_signing_signers.requestId, request.id)).orderBy(asc(ja_signing_signers.order)),
    db.select().from(ja_signing_audit).where(eq(ja_signing_audit.requestId, request.id)).orderBy(asc(ja_signing_audit.createdAt)),
    db.select({ firstName: ja_users.firstName, lastName: ja_users.lastName, email: ja_users.email }).from(ja_users).where(eq(ja_users.id, userId as number)).limit(1),
    db.select({ value: ja_site_settings.value }).from(ja_site_settings).where(eq(ja_site_settings.settingKey, 'site_name')).limit(1),
  ]);

  const owner = ownerRows[0];
  const siteName = siteNameRow[0]?.value ?? 'JA Document Hub';
  const ownerName = owner ? `${owner.firstName} ${owner.lastName}` : 'Unknown';
  const now = new Date().toLocaleString('en-GB', { timeZone: 'Europe/London', dateStyle: 'long', timeStyle: 'long' });

  const signerRows = signers.map(s => `
    <tr>
      <td>${s.name}</td>
      <td>${s.email}</td>
      <td>${s.role ?? '—'}</td>
      <td>${s.status}</td>
      <td>${s.signedAt ? new Date(s.signedAt).toLocaleString('en-GB') : '—'}</td>
      <td>${s.ipAddress ?? '—'}</td>
    </tr>`).join('');

  const auditRows = audit.map(a => `
    <tr>
      <td>${new Date(a.createdAt).toLocaleString('en-GB')}</td>
      <td><code>${a.event}</code></td>
      <td>${a.signerEmail ?? (a.userId ? 'Owner' : a.adminId ? 'Admin' : '—')}</td>
      <td>${a.ipAddress ?? '—'}</td>
      <td>${a.detail ?? '—'}</td>
    </tr>`).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Audit Certificate — ${request.title}</title>
<style>
  body{font-family:Arial,sans-serif;font-size:12px;color:#111;margin:40px}
  h1{font-size:20px;color:#1B4F8A;border-bottom:2px solid #1B4F8A;padding-bottom:8px}
  h2{font-size:14px;color:#1B4F8A;margin-top:24px}
  table{width:100%;border-collapse:collapse;margin-top:8px}
  th{background:#1B4F8A;color:#fff;padding:6px 10px;text-align:left;font-size:11px}
  td{padding:5px 10px;border-bottom:1px solid #e5e7eb;font-size:11px}
  tr:nth-child(even) td{background:#f9fafb}
  .meta{background:#f0f4ff;border:1px solid #c7d7f5;border-radius:6px;padding:14px;margin:16px 0}
  .meta p{margin:4px 0;font-size:12px}
  .hash{font-family:monospace;font-size:10px;word-break:break-all;background:#f3f4f6;padding:4px 8px;border-radius:4px}
  .footer{margin-top:40px;border-top:1px solid #e5e7eb;padding-top:12px;font-size:10px;color:#6b7280}
  .status-completed{color:#166534;font-weight:bold}
</style>
</head>
<body>
<h1>Audit Certificate — Document Signing</h1>
<div class="meta">
  <p><strong>Document:</strong> ${request.title}</p>
  <p><strong>Request ID:</strong> ${request.uuid}</p>
  <p><strong>Owner:</strong> ${ownerName} (${owner?.email ?? ''})</p>
  <p><strong>Status:</strong> <span class="status-completed">${request.status.toUpperCase()}</span></p>
  <p><strong>Created:</strong> ${new Date(request.createdAt).toLocaleString('en-GB')}</p>
  ${request.completedAt ? `<p><strong>Completed:</strong> ${new Date(request.completedAt).toLocaleString('en-GB')}</p>` : ''}
  ${request.documentHash ? `<p><strong>Document SHA-256:</strong> <span class="hash">${request.documentHash}</span></p>` : ''}
  <p><strong>Certificate generated:</strong> ${now}</p>
</div>

<h2>Signers</h2>
<table>
  <thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Signed At</th><th>IP Address</th></tr></thead>
  <tbody>${signerRows}</tbody>
</table>

<h2>Audit Trail</h2>
<table>
  <thead><tr><th>Timestamp</th><th>Event</th><th>Actor</th><th>IP Address</th><th>Detail</th></tr></thead>
  <tbody>${auditRows}</tbody>
</table>

<div class="footer">
  <p>This certificate was generated by ${siteName} on ${now}.</p>
  <p>This document provides a tamper-evident record of the signing process. The document hash above can be used to verify the integrity of the original document.</p>
</div>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="audit-certificate-${request.uuid}.html"`);
  return res.send(html);
}
